name: docker

on:
  push:
    branches: [ "main" ]

jobs:
  Deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}

      - name: Build
        run: |
          cd openrasp/ && docker build -t  registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:openrasp-v2 .
          cd ../webgoat/ && docker build -t  registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:webgoat-v2 .
          cd ../BenchmarkJava/ && docker build -t  registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:benchmark-v2 .
          cd ../iast-jar/ && docker build -t  registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:iast-jar-v2 .
          cd ../iast-grpc-java/ && docker build -t  registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:iast-grpc-java-v2 .
      - name: push
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 600
          max_attempts: 10

          command: |
            docker push registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:openrasp-v2
            docker push registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:webgoat-v2
            docker push registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:benchmark-v2
            docker push registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:iast-jar-v2
            docker push registry.cn-hangzhou.aliyuncs.com/tscuite/bachang:iast-grpc-java-v2
